spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springAPI?useSSL=false
    username: root
    password: rushh

  jpa:
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL5InnoDBDialect

  jpa.hibernate.ddl-auto: create  


